### ISSUE TITLE
Latest PR - All Conversions Broken

### ISSUE THREAD

**Issue by app-generator** [app-generator/devtool-python-converter#30]
In the latest bulk commit, all conversions seem broken:

```log
Uncaught ReferenceError: output is not defined
    at sendDroppedDataWrapper (converter.js:741:29)
    at HTMLButtonElement.sendDataWrapper (converter.js:776:5)
```

The issue might be caused by `sendDroppedDataWrapper()`

![image](https://user-images.githubusercontent.com/51070104/209825585-ef2d6e73-6aee-419f-a085-9e2cdd443bf1.png)

**Comment by app-generator** [comment]
Tested & Validated using

[v1.0.7](https://github.com/app-generator/devtool-python-converter/releases) 

Ty!
